### ISSUE TITLE
[Bug] failed to update user profile

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#120]
**Describe the bug**
A new user cannot sign in.

**To Reproduce**
1. Go to the website
2. Click on sign in
3. User authenticate with Google, but redirect to sign in page again

**Expected behavior**
User is signed in and redirect to https://devlaunchers.org/users/me

**Environment**
Staging and production

**Additional context**
```
[2023-12-06 22:34:19.111] [31merror[39m: Cannot read properties of null (reading 'url')
TypeError: Cannot read properties of null (reading 'url')
at Object.afterUpdate (/srv/app/src/api/profile/content-types/profile/lifecycles.js:6:60)
at modelsLifecyclesSubscriber (/srv/app/node_modules/@strapi/database/lib/lifecycles/subscribers/models-lifecycles.js:15:41)
at Object.run (/srv/app/node_modules/@strapi/database/lib/lifecycles/index.js:62:17)
at Object.update (/srv/app/node_modules/@strapi/database/lib/entity-manager/index.js:343:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.update (/srv/app/node_modules/@strapi/strapi/lib/services/entity-service/index.js:223:18)
at async Object.<anonymous> (/srv/app/node_modules/@strapi/strapi/lib/services/entity-service/index.js:415:20)
at async Object.publish (/srv/app/node_modules/@strapi/plugin-content-manager/server/services/entity-manager.js:186:27)
at async Object.publish (/srv/app/node_modules/@strapi/plugin-content-manager/server/controllers/collection-types.js:262:20)
at async returnBodyMiddleware (/srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
```

**Comment by chrismferguson** [comment]
Issue has been fixed.
