### ISSUE TITLE
[Bug] Update user interest returns 500 response

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#134]
**Describe the bug**
The frontend cannot update user interest because the API returns 500

**To Reproduce**
1. Login to the website https://devlaunchers.org
2. Open your browser's network tab
3. Click on an interest
4. See PUT https://apiv4.devlaunchers.org/api/users/<user ID> returns 500

**Expected behavior**
The API returns 200 and update user interests successfully

**Environment**
Staging and production

**Additional context**
Strapi log:
```
TypeError: Cannot read properties of undefined (reading 'connect')
at Object.beforeUpdate (/srv/app/src/index.js:46:50)
at Object.run (/srv/app/node_modules/@strapi/database/dist/index.js:5952:37)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.update (/srv/app/node_modules/@strapi/database/dist/index.js:5064:22)
at async Object.update (/srv/app/node_modules/@strapi/strapi/dist/services/entity-service/index.js:170:18)
at async Object.<anonymous> (/srv/app/node_modules/@strapi/strapi/dist/services/entity-service/index.js:309:18)
at async Object.update (/srv/app/node_modules/@strapi/plugin-users-permissions/server/controllers/user.js:142:18)
at async returnBodyMiddleware (/srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
at async policiesMiddleware (/srv/app/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
at async /srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
```

**Comment by tiagopazhs** [comment]
As we already solve this on #157 , I will close this.
