### ISSUE TITLE
[Bug] logout endpoint returns 500

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#138]
**Describe the bug**
Users cannot logout from the website because the endpoint returns 500

**To Reproduce**
1. Go to https://apiv4.devlaunchers.org/api/auth/logout
2. Return 500 error

**Expected behavior**
The endpoint returns 200

**Environment**
Staging and production

**Additional context**
Logs:
```
[2024-01-17 22:06:35.097] [31merror[39m: Forbidden access
ForbiddenError: Forbidden access
at Object.verify (/srv/app/node_modules/@strapi/plugin-users-permissions/server/strategies/users-permissions.js:106:11)
at Object.verify (/srv/app/node_modules/@strapi/strapi/dist/services/auth/index.js:75:30)
at /srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:26:23
at dispatch (/srv/app/node_modules/koa-compose/index.js:42:32)
at Object.authenticate (/srv/app/node_modules/@strapi/strapi/dist/services/auth/index.js:62:18)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async serve (/srv/app/node_modules/koa-static/index.js:59:5)
at async returnBodyMiddleware (/srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
at async policiesMiddleware (/srv/app/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
at async /srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:27:12
```

**Comment by chungthuang** [comment]
The problem was authenticated didn't have permission to call the logout endpoint.
