### ISSUE TITLE
[Bug] Cannot submit comments for ideas in staging

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#148]
**Describe the bug**
Cannot submit comments for ideas in staging

**To Reproduce**
1. Go to https://staging.devlaunchers.org/ideaspace/workshop/254
2. Open network tab of the browser
3. Write a comment and try to submit it
4. See POST `https://apiv4-staging.devlaunchers.org/api/comments` got a 500 response

**Expected behavior**
Idea is submitted

**Environment**
Staging website which uses the staging API

**Additional context**
Staging server log suggests the problem is in the lifecycle hook:
```
{
id: 180,
text: 'Can you provide more details?',
author: 'cthuang',
createdAt: '2024-02-15T20:22:14.175Z',
updatedAt: '2024-02-15T20:22:14.175Z',
publishedAt: '2024-02-15T20:22:14.136Z'
}
[2024-02-15 20:22:14.420] [31merror[39m: Cannot read properties of undefined (reading 'ideaName')
TypeError: Cannot read properties of undefined (reading 'ideaName')
at Object.afterCreate (/srv/app/src/api/comment/content-types/comment/lifecycles.js:10:56)
at modelsLifecyclesSubscriber (/srv/app/node_modules/@strapi/database/dist/index.js:5856:43)
at Object.run (/srv/app/node_modules/@strapi/database/dist/index.js:5941:17)
at Object.create (/srv/app/node_modules/@strapi/database/dist/index.js:5038:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.create (/srv/app/node_modules/@strapi/strapi/dist/services/entity-service/index.js:131:18)
at async Object.<anonymous> (/srv/app/node_modules/@strapi/strapi/dist/services/entity-service/index.js:309:18)
at async Object.create (/srv/app/node_modules/@strapi/strapi/dist/core-api/controller/collection-type.js:46:22)
at async returnBodyMiddleware (/srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:42:18)
at async policiesMiddleware (/srv/app/node_modules/@strapi/strapi/dist/services/server/policy.js:15:5)
```

**Comment by becevka** [comment]
Testing through Postman.

- Update .env and follow instructions how to start test environment in README.md
- Login to Strapi Content Manager
- Create new Idea Card and publish
- In postman run POST http://localhost:1337/api/auth/local with body 
``` {
  "identifier": "integration-test@devlaunchers.org",
  "password": "integration-test"
}```
- and then test using POST http://localhost:1337/api/comments with body like this
```
{"data":{"author":"me","idea_card":{"id":1},"text":"more test"}}
```

**Comment by becevka** [comment]
This has been already taken care of by https://app.zenhub.com/workspaces/platform-team-631b73fa4dada357304fe853/issues/gh/dev-launchers/strapiv4/158. Closing ticket.
