### ISSUE TITLE
[Bug] "An error occurred while uploading the file." in local development mode

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/strapiv4#150]
**Describe the bug**
when trying to upload assets to the media library in development environment you get
`An error occurred while uploading the file.`

**To Reproduce**
1. Go to content management
2. Click on profile [or any collection that has relationship to media manager]
3. Try to upload an image to the to that entity

Node.js returns this error in the terminal
```
strapiv4/node_modules/@azure/storage-blob/dist/index.js:23787
            throw new Error("Unable to extract containerName with provided information.");
                  ^

Error: Unable to extract containerName with provided information.
    at ContainerClient.getContainerNameFromUrl (/home/momaqbol/strapiv4/node_modules/@azure/storage-blob/dist/index.js:23787:19)
    at new ContainerClient (/home/momaqbol/strapiv4/node_modules/@azure/storage-blob/dist/index.js:22638:36)
    at BlobServiceClient.getContainerClient (/home/momaqbol/strapiv4/node_modules/@azure/storage-blob/dist/index.js:24363:16)
    at /home/momaqbol/strapiv4/node_modules/strapi-provider-upload-azure-storage/dist/index.js:38:47
    at Generator.next (<anonymous>)
    at /home/momaqbol/strapiv4/node_modules/strapi-provider-upload-azure-storage/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/momaqbol/strapiv4/node_modules/strapi-provider-upload-azure-storage/dist/index.js:4:12)
    at handleUpload (/home/momaqbol/strapiv4/node_modules/strapi-provider-upload-azure-storage/dist/index.js:36:12)
    at Object.uploadStream (/home/momaqbol/strapiv4/node_modules/strapi-provider-upload-azure-storage/dist/index.js:91:24)

Node.js v18.4.0
```
**Expected behavior**
image gets uploaded

**Screenshots**
![image](https://github.com/dev-launchers/strapiv4/assets/27841994/54da2a9f-854a-40b0-9b30-5244fe36b909)

**Environment**
OS: PopOS
Browser: Librefox
Node: v18.4.0

**Comment by chungthuang** [comment]
What is your `NODE_ENV`? The storage provider used by strapi depends on the `NODE_ENV`. For development, it's using Storage used when `NODE_ENV=development` https://github.com/dev-launchers/strapiv4/blob/main/config/env/development/plugins.js#L2-L7. For all other environment, it's using Azure blob storage https://github.com/dev-launchers/strapiv4/blob/main/config/plugins.js#L2-L14.

**Comment by Enjoy2Live** [comment]
> What is your `NODE_ENV`? The storage provider used by strapi depends on the `NODE_ENV`. For development, it's using Storage used when `NODE_ENV=development` https://github.com/dev-launchers/strapiv4/blob/main/config/env/development/plugins.js#L2-L7. For all other environment, it's using Azure blob storage https://github.com/dev-launchers/strapiv4/blob/main/config/plugins.js#L2-L14.

my `NODE_ENV` is development, I think there's some sort of conflict because it doesn't use Storage in `NODE_ENV=development` at least on my machine!
