### ISSUE TITLE
Send Exceptions to Sentry

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#25]
The server is logging errors such as
```
InternalServerError: https://devlaunchers.com is not a valid origin
at Object.throw (/srv/app/node_modules/koa/lib/context.js:97:11)
at Object.origin (/srv/app/node_modules/strapi/lib/middlewares/cors/index.js:52:31)
at cors (/srv/app/node_modules/@koa/cors/index.js:60:24)
at dispatch (/srv/app/node_modules/koa-compose/index.js:42:32)
at /srv/app/node_modules/strapi/lib/middlewares/responseTime/index.js:17:15
at dispatch (/srv/app/node_modules/koa-compose/index.js:42:32)
at /srv/app/node_modules/strapi/lib/services/metrics/middleware.js:29:11
at dispatch (/srv/app/node_modules/koa-compose/index.js:42:32)
at /srv/app/node_modules/strapi/lib/Strapi.js:325:15
at dispatch (/srv/app/node_modules/koa-compose/index.js:42:32)
at /srv/app/node_modules/koa-compose/index.js:34:12
at Application.handleRequest (/srv/app/node_modules/koa/lib/application.js:168:12)
at Strapi.handleRequest [as requestHandler] (/srv/app/node_modules/koa/lib/application.js:150:19)
at Strapi.handleRequest (/srv/app/node_modules/strapi/lib/Strapi.js:86:17)
at Server.emit (events.js:315:20)
at parserOnIncoming (_http_server.js:874:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
```
But we are not noticing it because no one is actively monitoring logs. Integrating with sentry https://strapi.io/blog/introducing-sentry-plugin will improve our observability.

**Comment by chungthuang** [comment]
I saw some events sent to Sentry and created https://github.com/dev-launchers/strapiv4/issues/91 and https://github.com/dev-launchers/strapiv4/issues/92. So Sentry integration is working!

**Comment by chungthuang** [comment]
The errors are sent to Dev Launchers Sentry.
